// Mocks generated by Mockito 5.4.6 from annotations
// in echoai/test/providers/settings_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:echoai/models/conversation.dart' as _i8;
import 'package:echoai/models/message.dart' as _i6;
import 'package:echoai/models/settings.dart' as _i9;
import 'package:echoai/services/database_service.dart' as _i3;
import 'package:echoai/utils/result.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i3.DatabaseService {
  @override
  _i4.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i4.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i4.Future<_i2.Database>);

  @override
  _i4.Future<_i5.Result<void>> saveMessage(_i6.Message? message) =>
      (super.noSuchMethod(
            Invocation.method(#saveMessage, [message]),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#saveMessage, [message]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#saveMessage, [message]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);

  @override
  _i4.Future<_i5.Result<List<_i6.Message>>> getMessages(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, [conversationId]),
            returnValue: _i4.Future<_i5.Result<List<_i6.Message>>>.value(
              _i7.dummyValue<_i5.Result<List<_i6.Message>>>(
                this,
                Invocation.method(#getMessages, [conversationId]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Result<List<_i6.Message>>>.value(
                  _i7.dummyValue<_i5.Result<List<_i6.Message>>>(
                    this,
                    Invocation.method(#getMessages, [conversationId]),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<List<_i6.Message>>>);

  @override
  _i4.Future<_i5.Result<void>> updateMessage(_i6.Message? message) =>
      (super.noSuchMethod(
            Invocation.method(#updateMessage, [message]),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#updateMessage, [message]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#updateMessage, [message]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);

  @override
  _i4.Future<_i5.Result<void>> deleteMessage(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [messageId]),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#deleteMessage, [messageId]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#deleteMessage, [messageId]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);

  @override
  _i4.Future<_i5.Result<void>> saveConversation(
    _i8.Conversation? conversation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveConversation, [conversation]),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#saveConversation, [conversation]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#saveConversation, [conversation]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);

  @override
  _i4.Future<_i5.Result<List<_i8.Conversation>>> getAllConversations({
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllConversations, [], {#limit: limit}),
            returnValue: _i4.Future<_i5.Result<List<_i8.Conversation>>>.value(
              _i7.dummyValue<_i5.Result<List<_i8.Conversation>>>(
                this,
                Invocation.method(#getAllConversations, [], {#limit: limit}),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Result<List<_i8.Conversation>>>.value(
                  _i7.dummyValue<_i5.Result<List<_i8.Conversation>>>(
                    this,
                    Invocation.method(#getAllConversations, [], {
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<List<_i8.Conversation>>>);

  @override
  _i4.Future<_i5.Result<_i8.Conversation>> getConversation(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversation, [conversationId]),
            returnValue: _i4.Future<_i5.Result<_i8.Conversation>>.value(
              _i7.dummyValue<_i5.Result<_i8.Conversation>>(
                this,
                Invocation.method(#getConversation, [conversationId]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Result<_i8.Conversation>>.value(
                  _i7.dummyValue<_i5.Result<_i8.Conversation>>(
                    this,
                    Invocation.method(#getConversation, [conversationId]),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<_i8.Conversation>>);

  @override
  _i4.Future<_i5.Result<void>> updateConversation(
    _i8.Conversation? conversation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateConversation, [conversation]),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#updateConversation, [conversation]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#updateConversation, [conversation]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);

  @override
  _i4.Future<_i5.Result<void>> deleteConversation(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversation, [conversationId]),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#deleteConversation, [conversationId]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#deleteConversation, [conversationId]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);

  @override
  _i4.Future<_i5.Result<void>> deleteAllConversations() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllConversations, []),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#deleteAllConversations, []),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#deleteAllConversations, []),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);

  @override
  _i4.Future<_i5.Result<List<_i8.Conversation>>> searchConversations(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchConversations, [query]),
            returnValue: _i4.Future<_i5.Result<List<_i8.Conversation>>>.value(
              _i7.dummyValue<_i5.Result<List<_i8.Conversation>>>(
                this,
                Invocation.method(#searchConversations, [query]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Result<List<_i8.Conversation>>>.value(
                  _i7.dummyValue<_i5.Result<List<_i8.Conversation>>>(
                    this,
                    Invocation.method(#searchConversations, [query]),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<List<_i8.Conversation>>>);

  @override
  _i4.Future<_i5.Result<_i9.Settings>> getSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getSettings, []),
            returnValue: _i4.Future<_i5.Result<_i9.Settings>>.value(
              _i7.dummyValue<_i5.Result<_i9.Settings>>(
                this,
                Invocation.method(#getSettings, []),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Result<_i9.Settings>>.value(
                  _i7.dummyValue<_i5.Result<_i9.Settings>>(
                    this,
                    Invocation.method(#getSettings, []),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<_i9.Settings>>);

  @override
  _i4.Future<_i5.Result<void>> saveSettings(_i9.Settings? settings) =>
      (super.noSuchMethod(
            Invocation.method(#saveSettings, [settings]),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#saveSettings, [settings]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#saveSettings, [settings]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);

  @override
  _i4.Future<_i5.Result<int>> getConversationCount() =>
      (super.noSuchMethod(
            Invocation.method(#getConversationCount, []),
            returnValue: _i4.Future<_i5.Result<int>>.value(
              _i7.dummyValue<_i5.Result<int>>(
                this,
                Invocation.method(#getConversationCount, []),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i5.Result<int>>.value(
              _i7.dummyValue<_i5.Result<int>>(
                this,
                Invocation.method(#getConversationCount, []),
              ),
            ),
          )
          as _i4.Future<_i5.Result<int>>);

  @override
  _i4.Future<_i5.Result<int>> getTotalMessageCount() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalMessageCount, []),
            returnValue: _i4.Future<_i5.Result<int>>.value(
              _i7.dummyValue<_i5.Result<int>>(
                this,
                Invocation.method(#getTotalMessageCount, []),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i5.Result<int>>.value(
              _i7.dummyValue<_i5.Result<int>>(
                this,
                Invocation.method(#getTotalMessageCount, []),
              ),
            ),
          )
          as _i4.Future<_i5.Result<int>>);

  @override
  _i4.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.Result<void>> deleteDatabase() =>
      (super.noSuchMethod(
            Invocation.method(#deleteDatabase, []),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#deleteDatabase, []),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#deleteDatabase, []),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);
}
